FROM debian:bookworm

RUN apt-get update && apt-get upgrade -y && apt-get install redis-server redis-tools -y
RUN rm -rf /var/lib/apt/lists/*

COPY conf/redis.conf /etc/redis/redis.conf

EXPOSE 6379

CMD [ "redis-server", "/etc/redis/redis.conf" ]